POST http://localhost:9999/payments
Content-Type: application/json

{
  "correlationId": "fee10853-1849-4fd0-9f55-1d2b6f6cc77c",
  "amount": 1000.00
}
###

GET http://localhost:9999/payments-summary
###